local headers = require("mods").requireFromPlugin("libraries.goober.headers")

-- this file is automatically generated with Options/OptionsManager.LuaGenerator.cs
-- 
-- please dont try to tweak it yourself when adding an option; open celesterepl or
-- the c# debug console mod idr what it was called and execute the following line:
-- Celeste.Mod.GooberHelper.OptionsManager.GenerateLuaOptions()
-- 
-- after that, paste the new content on your clipboard into this file

return {
	headers.categoryHeader("Jumping"),
	headers.groupHeader("SpeedPreservation"),
	"CobwobSpeedInversion: [None|RequireSpeed|WorkWithRetention]",
	"JumpInversion: [None|GroundJumps|All]",
	"WalljumpSpeedPreservation: [None|FakeRCB|Preserve|Invert]",
	"WallbounceSpeedPreservation",
	"HyperAndSuperSpeedPreservation",
	"UpwardsJumpSpeedPreservationThreshold: [number|None|DashSpeed]",
	"DownwardsJumpSpeedPreservationThreshold: [number|None|DashSpeed]",
	"BounceHelperBounceSpeedPreservation",

	headers.groupHeader("NewThings"),
	"GetClimbjumpSpeedInRetention",
	"AdditiveVerticalJumpSpeed",
	"SwapHorizontalAndVerticalSpeedOnWalljump",
	"VerticalToHorizontalSpeedOnGroundJump: [None|Vertical|Magnitude]",
	"CornerboostBlocksEverywhere",

	headers.groupHeader("AllowingThings"),
	"AllDirectionHypersAndSupers: [None|RequireGround|WorkWithCoyoteTimeAndDontRefill|WorkWithCoyoteTime]",
	"AllowUpwardsCoyote",
	"AllDirectionDreamJumps",
	"AllowHoldableClimbjumping",

	headers.categoryHeader("Dashing"),
	headers.groupHeader("SpeedPreservation"),
	"VerticalDashSpeedPreservation",
	"ReverseDashSpeedPreservation",

	headers.groupHeader("NewThings"),
	"MagnitudeBasedDashSpeed: [None|OnlyCardinal|All]",

	headers.groupHeader("AllowingThings"),
	"DashesDontResetSpeed: [None|Legacy|On]",
	"KeepDashAttackOnCollision",
	"DownDemoDashing",

	headers.categoryHeader("Moving"),
	headers.groupHeader("SpeedPreservation"),
	"HorizontalTurningSpeedInversion",
	"VerticalTurningSpeedInversion",
	
	headers.groupHeader("NewThings"),
	"WallboostDirectionIsOppositeSpeed",
	"WallboostSpeedIsOppositeSpeed",
	"DownwardsAirFrictionBehavior",
	"IgnoreForcemove",
	
	headers.categoryHeader("Entities"),
	headers.groupHeader("Special"),
	"RefillFreezeLength: [number]",
	
	headers.groupHeader("SpeedPreservation"),
	"DreamBlockSpeedPreservation: [None|Horizontal|Vertical|Both|Magnitude]",
	"SpringSpeedPreservation: [None|Preserve|Invert]",
	"ReboundSpeedPreservation",
	"PointBounceSpeedPreservation",
	"ReflectBounceSpeedInversion",
	"ExplodeLaunchSpeedPreservation: [None|Horizontal|Vertical|Both|Magnitude]",
	"PickupSpeedInversion",
	"BubbleSpeedPreservation",
	"FeatherEndSpeedPreservation",
	"BadelineBossSpeedPreservation: [None|Preserve|Invert|Aim]",
	
	headers.groupHeader("NewThings"),
	"CustomFeathers: [None|KeepIntro|SkipIntro]",
	"CustomSwimming",
	"CustomSwimmingWalljumpSpeed: [number|Off]",
	"CustomSwimmingLaunchSpeed: [number]",
	"CustomSwimmingLaunchThreshold: [number|Off]",
	"LenientStunning",
	"HoldableSpeedInheritanceHorizontal: [number|None|MatchPlayer]",
	"HoldableSpeedInheritanceVertical: [number|None|MatchPlayer]",
	"ReverseBackboosts",
	
	headers.groupHeader("AllowingThings"),
	"AllowCrouchedHoldableGrabbing",
	"CoreBlockAllDirectionActivation",
	
	headers.categoryHeader("Other"),
	headers.groupHeader("Special"),
	"RetentionLength: [number]",
	
	headers.groupHeader("SpeedPreservation"),
	"ConserveBeforeDashSpeed",
	"ClimbingSpeedPreservation",
	"UpwardsTransitionSpeedPreservation",

	headers.groupHeader("NewThings"),
	"FastFallHitboxSquish: [number]",
	"LiftboostAdditionHorizontal: [number]",
	"LiftboostAdditionVertical: [number]",
	"AdvantageousLiftboost",
	"StackableUltras",

	headers.groupHeader("AllowingThings"),
	"AllowUpwardsClimbGrabbing: [None|WhileHoldingUp|Always]",
	"AllowCrouchedClimbGrabbing",
	"AllowClimbingInDashState",
	"AllowWindWhileDashing: [None|Velocity|Speed]",
	"RemoveNormalEnd",

	headers.categoryHeader("Visuals"),
	headers.groupHeader("NewThings"),
	"PlayerShaderMask: [None|HairOnly|Cover]",
	"TheoNuclearReactor",
	"RotatePlayerToSpeed",
	"CustomSwimmingAnimation",

	headers.categoryHeader("Miscellaneous"),
	headers.groupHeader("NewThings"),
	"AlwaysExplodeSpinners",
	"GoldenBlocksAlwaysLoad",
	"RefillFreezeGameSuspension",
	"BufferDelayVisualization",
	"Ant",

	headers.categoryHeader("General"),
	"ShowActiveOptions",
}